spring:
  application:
    name: eureka-server-release
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server-release.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
